export const newsItems = [
  {
    id: 1,
    title: "Bank Indonesia Pertahankan Suku Bunga Acuan di Level 5,75%",
    excerpt: "Bank Indonesia memutuskan untuk mempertahankan suku bunga acuan BI Rate di level 5,75% dalam Rapat Dewan Gubernur (RDG) bulan ini.",
    date: "12 Mei 2025",
    readTime: "3 menit",
    image: "https://images.pexels.com/photos/4386366/pexels-photo-4386366.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 2,
    title: "Saham Teknologi Indonesia Naik Signifikan Setelah Laporan Keuangan Q1",
    excerpt: "Sektor teknologi mencatat kenaikan signifikan setelah beberapa perusahaan teknologi besar melaporkan kinerja keuangan kuartal pertama yang melampaui ekspektasi.",
    date: "10 Mei 2025",
    readTime: "4 menit",
    image: "https://images.pexels.com/photos/7563687/pexels-photo-7563687.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 3,
    title: "Pertumbuhan Ekonomi Indonesia Capai 5,2% di Kuartal Pertama 2025",
    excerpt: "Badan Pusat Statistik (BPS) melaporkan pertumbuhan ekonomi Indonesia mencapai 5,2% pada kuartal pertama 2025, melampaui proyeksi ekonom.",
    date: "8 Mei 2025",
    readTime: "5 menit",
    image: "https://images.pexels.com/photos/1036808/pexels-photo-1036808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 4,
    title: "IHSG Tembus Level 7.500 untuk Pertama Kalinya dalam Sejarah",
    excerpt: "Indeks Harga Saham Gabungan (IHSG) mencatat rekor baru dengan menembus level 7.500 untuk pertama kalinya dalam sejarah pasar modal Indonesia.",
    date: "5 Mei 2025",
    readTime: "3 menit",
    image: "https://images.pexels.com/photos/5980865/pexels-photo-5980865.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 5,
    title: "Bank BUMN Catat Pertumbuhan Kredit 15% di Kuartal Pertama 2025",
    excerpt: "Empat bank BUMN terbesar Indonesia mencatat pertumbuhan kredit rata-rata sebesar 15% pada kuartal pertama 2025, menunjukkan pemulihan ekonomi yang kuat.",
    date: "3 Mei 2025",
    readTime: "4 menit",
    image: "https://images.pexels.com/photos/6774977/pexels-photo-6774977.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 6,
    title: "Pemerintah Luncurkan Kebijakan Baru untuk Mendorong Investasi di Pasar Modal",
    excerpt: "Pemerintah Indonesia meluncurkan serangkaian kebijakan baru yang bertujuan untuk mendorong pertumbuhan investasi di pasar modal domestik.",
    date: "1 Mei 2025",
    readTime: "6 menit",
    image: "https://images.pexels.com/photos/8370428/pexels-photo-8370428.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 7,
    title: "Saham Energi Terbarukan Meroket Setelah Pengumuman Kebijakan Energi Nasional",
    excerpt: "Saham perusahaan energi terbarukan di Indonesia mencatat kenaikan signifikan setelah pemerintah mengumumkan kebijakan energi nasional terbaru.",
    date: "29 Apr 2025",
    readTime: "4 menit",
    image: "https://images.pexels.com/photos/1402850/pexels-photo-1402850.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 8,
    title: "OJK Terbitkan Aturan Baru untuk Perlindungan Investor Ritel",
    excerpt: "Otoritas Jasa Keuangan (OJK) menerbitkan aturan baru yang bertujuan untuk meningkatkan perlindungan investor ritel di pasar modal Indonesia.",
    date: "27 Apr 2025",
    readTime: "5 menit",
    image: "https://images.pexels.com/photos/6781003/pexels-photo-6781003.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
];